//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvedio {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_String() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jvedio.Resource_String", typeof(Resource_String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCADIAJMDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BaseImage64 {
            get {
                return ResourceManager.GetString("BaseImage64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ABBA,ABP,ABS,AD,ADN,ADV,ADVF,ADVO,ADZ,AED,AEDVD,AGEMIX,AJVR,AKHO,ALB,ALD,AMBI,AMD,ANB,AND,ANND,ANX,ANZI,AOZ,AP,APAA,APAK,APKH,APNS,ARA,ARATHD,ARD,ARM,ARMD,ARMG,ARN,ARSO,ASFB,AST,ASW,ATAD,ATFB,ATID,ATKD,ATOM,AUKG,AUKS,AV,AVD,AVGP,AVKH,AVOP,AVOPVR,AVSA,AVVR,AW,AWD,AWT,BAGBD,BAZX,BBAN,BBBN,BBI,BC,BCDP,BCPV,BDA,BDMILD,BDSR,BEB,BF,BGSD,BIB,BIG,BIJN,BIKMVR,BKD,BKSP,BLK,BLOR,BMD,BMVR,BMW,BNDV,BNSPS,BOB,BOBB,BOIN,BOKD,BOMN,BRD,BTD,BTR,BTYD,BUR,C,CABD,CABE,CACA,CADV,CAFR,CAMI,CAND,CAPI,CB,CC,CCX,CEAD,CESD,CETD,CHN,C [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Censored {
            get {
                return ResourceManager.GetString("Censored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流出,留出,泄露,泄密,曝光,flowout 的本地化字符串。
        /// </summary>
        internal static string FLOWOUT {
            get {
                return ResourceManager.GetString("FLOWOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折磨,嘔吐,觸手,蠻橫嬌羞,處男,正太控,出軌,瘙癢,運動,女同接吻,性感的,美容院,處女,爛醉如泥的,殘忍畫面,妄想,惡作劇,學校作品,粗暴,通姦,姐妹,雙性人,跳舞,性奴,倒追,性騷擾,其他,戀腿癖,偷窥,花癡,男同性恋,情侶,戀乳癖,亂倫,其他戀物癖,偶像藝人,野外・露出,獵豔,女同性戀,企畫,10枚組,性感的,性感的,科幻,女優ベスト・総集編,温泉,M男,原作コラボ,16時間以上作品,デカチン・巨根,ファン感謝・訪問,動画,巨尻,ハーレム,日焼け,早漏,キス・接吻,汗だく,スマホ専用縦動画,Vシネマ,Don Cipote&apos;s choice,アニメ,アクション,イメージビデオ（男性）,孕ませ,ボーイズラブ,ビッチ,特典あり（AVベースボール）,コミック雑誌,時間停止|童年朋友,公主,亞洲女演員,伴侶,講師,婆婆,格鬥家,女檢察官,明星臉,女主人、女老板,模特兒,秘書,美少女,新娘、年輕妻子,姐姐,格鬥家,車掌小姐,寡婦,千金小姐,白人,已婚婦女,女醫生,各種職業,妓女,賽車女郎,女大學生,展場女孩,女教師,母親,家教,护士,蕩婦,黑人演員,女生,女主播,高中女生,服務生,魔法少女,學生（其他）,動畫人物 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GenreCensored {
            get {
                return ResourceManager.GetString("GenreCensored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非同性戀,撩撥性,迷人,陰道擴張,體液,戀腿癖,工作性幻想,戀足癖,戶外,戀物癖,面紅耳赤,控制,軟色情,乳液,夫妻性幻想,洗澡,FFM,運動,手銬,拙劣的模仿,幕後花絮,狂歡,真實,科幻,歐洲,第一個男孩 / 女孩,公共性,屄,通姦,施工,婚禮,潤滑油,性交,同性戀,出軌,奇聞趣事|青年人,人妻,競技,媽媽,女商人,護士,女學生,老師,學生,烏木,秘書,施虐者,老闆,繼母,刑事,客戶,女友,警察,女僕,啦啦隊長,脫衣舞女,性治療師,繼女,小姐,特務,軍人,妻子,戰士女孩,角色扮演,奴隸,按摩師,囚犯,商店營業員,浪蕩公子,校長,廚師,機械師,孕婦,追星族,空姐,聖誕老人的助手,水手,超女,律師,救生員,消防員,女童子軍,水管工人,法官,奶女僕,芭蕾舞者,熟女,脫衣舞,素人,醫生 / 護士,少女,保姆,犠母妹|高跟鞋,比基尼泳裝,長襪,丁字褲,裙子,連衣裙,內褲,緊身短褲,襪子,牛仔褲,制服,戲服,靴子,鞋,連褲襪,平角褲,人字拖,超短裙,眼鏡,手套,打底褲,眼罩,運動鞋,睡衣,黑色絲襪,裸體絲襪,連體衣,彩色絲襪,襯衫,內衣,網襪|紋身,淺黑膚色的女人,金發女郎,白種人,中等的膚色,深棕色頭髮,褐色眼睛,金 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GenreEurope {
            get {
                return ResourceManager.GetString("GenreEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高清,字幕,推薦作品,通姦,淋浴,舌頭,下流,敏感,變態,願望,慾求不滿,服侍,外遇,訪問,性伴侶,保守,購物,誘惑,出差,煩惱,主動,再會,戀物癖,問題,騙奸,鬼混,高手,順從,密會,做家務,秘密,送貨上門,壓力,處女作,淫語,問卷,住一宿,眼淚,跪求,求職,婚禮,第一視角,洗澡,首次,劇情,約會,實拍,同性戀,幻想,淫蕩,旅行,面試,喝酒,尖叫,新年,借款,不忠,檢查,羞恥,勾引,新人,推銷,ブルマ|AV女優,情人,丈夫,辣妹,S級女優,白領,偶像,兒子,女僕,老師,夫婦,保健室,朋友,工作人員,明星,同事,面具男,上司,睡眠系,奶奶,播音員,鄰居,親人,店員,魔女,視訊小姐,大學生,寡婦,小姐,秘書,人妖,啦啦隊,美容師,岳母,警察,熟女,素人,人妻,痴女,角色扮演,蘿莉,姐姐,模特,教師,學生,少女,新手,男友,護士,媽媽,主婦,孕婦,女教師,年輕人妻,職員,看護,外觀相似,色狼,醫生,新婚,黑人,空中小姐|制服,內衣,休閒裝,水手服,全裸,不穿內褲,和服,不戴胸罩,連衣裙,打底褲,緊身衣,客人,晚禮服,治癒系,大衣,裸體襪子,絲帶,睡衣,面具,牛仔褲,喪服,極小比基尼,混血,毛衣,頸鏈,短褲,美人, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GenreUncensored {
            get {
                return ResourceManager.GetString("GenreUncensored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Jvedio {
            get {
                object obj = ResourceManager.GetObject("Jvedio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 3g2,3gp,3gp2,3gpp,amr,amv,asf,avi,bdmv,bik,d2v,divx,drc,dsa,dsm,dss,dsv,evo,f4v,flc,fli,flic,flv,hdmov,ifo,ivf,m1v,m2p,m2t,m2ts,m2v,m4b,m4p,m4v,mkv,mp2v,mp4,mp4v,mpe,mpeg,mpg,mpls,mpv2,mpv4,mov,mts,ogm,ogv,pss,pva,qt,ram,ratdvd,rm,rmm,rmvb,roq,rpm,smil,smk,swf,tp,tpr,ts,vob,vp6,webm,wm,wmp,wmv,nfo 的本地化字符串。
        /// </summary>
        internal static string ScanVetioType {
            get {
                return ResourceManager.GetString("ScanVetioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -,_,cd,hd,whole 的本地化字符串。
        /// </summary>
        internal static string SubSectionFeature {
            get {
                return ResourceManager.GetString("SubSectionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMBD,SMDV,BT,CCDV,CWDV,CWP,CWPBD,CWPD,CYC,DRC,DRG,DRGBD,DSAM,DSAMBD,DSAMD,HEY,HEYDOUGA,HEYZO,KP,KSC,LAF,LAFBD,LLDV,MCBD,MKBD,MKD,MXX,NIP,PT,RED,RHJ,S2M,S2MBD,S2MCR,SKY,SKYHD,SMD,SSDV,SSKP,FC2PPV,FC2,GACHI,GACHIG,NALGASCLUB,LL,KG,HAMESAMURAI,GACHIP 的本地化字符串。
        /// </summary>
        internal static string Uncensored {
            get {
                return ResourceManager.GetString("Uncensored", resourceCulture);
            }
        }
    }
}
